
WITH informacion_recaudo AS (
    select * from  tpagos_recaudo_nacional where TO_TIMESTAMP(FECHA_PAGO)  
    BETWEEN TO_TIMESTAMP('$FECHA_INICIO$', 'DD/MM/YYYY HH24:MI:SS') 
    AND TO_TIMESTAMP('$FECHA_FIN$', 'DD/MM/YYYY HH24:MI:SS') AND
    estado_pago='OK' AND operador is not null 
    AND USUARIO = 'TU_COMPRA' AND  NUMERO_RECIBO IS NOT NULL
)

SELECT PG.ID_PAGO AS ID_PAGO,
'open' AS GRUPO_PRODUCTO,
PG.CAJERO AS CAJERO,
(U.USER_NAME
|| ' '
|| U.LAST_NAME) AS NOMBRE_CAJERO,
TO_CHAR(PG.FECHA_CREACION,'DD/MM/YYYY HH24:mm:ss') AS FECHA_PAGO,
--PG.FECHA_CREACION AS FECHA_PAGO,
(SYSDATE) AS FECHA_GENERACION,  
FORMA_PAGO.DES_PAGO,
FORMA_PAGO.CONSECUTIVO AS ID_FORMA_PAGO,
(TSIRE_DETALLE_PAGO.VALOR) AS VALOR,
(SELECT SUM(VALOR)
FROM TSIRE_PAGOS P
WHERE P.NO_RECIBO=PG.NO_RECIBO
AND P.PRODUCTO =7
) AS CODIGO_BARRAS_OPEN,
(SELECT SUM(VALOR)
FROM TSIRE_PAGOS P
WHERE P.NO_RECIBO=PG.NO_RECIBO
AND P.PRODUCTO =41
) AS PAZ_ZALVO_OPEN,
(SELECT SUM(VALOR)
FROM TSIRE_PAGOS P
WHERE P.NO_RECIBO=PG.NO_RECIBO
AND P.PRODUCTO =47
) AS HONORARIOS_ABOGADO_OPEN,
(SELECT SUM(VALOR)
FROM TSIRE_PAGOS P
WHERE P.NO_RECIBO=PG.NO_RECIBO
AND P.PRODUCTO =50
) AS GASTOS_PROCESALES_OPEN_CARD,
'CAJA' AS CAJA,
UR.ROLE_ID,
NO_RECIBO AS RECIBO,
TRIM(PG.CEDULA_DEUDOR) AS CEDULA_DEUDOR,
DECODE(ANULADO,'S','ANULADO','APROBADO') AS ESTADO,
TRIM(TO_NUMBER(PG.NUMERO_COMPROBANTE)) AS COMPROBANTE,
TO_CHAR(PG.FECHA_CREACION,'HH:MI AM') AS HORA,
ID_LIQUI AS ID_LIQUIDACION,
'' AS OPERADOR,
'' AS usuario_terminal

FROM TSIRE_PAGOS PG,
TSIRE_DETALLE_PAGO,
TLIQCA_LIQUIDACION,
FORMA_PAGO,
LEAF_USER U,
LEAF_USER_ROLE UR
WHERE
(FORMA_PAGO.CONSECUTIVO = ((SELECT TPRN.FORMA_PAGO FROM TPAGOS_RECAUDO_NACIONAL TPRN where TPRN.NUMERO_RECIBO = PG.NO_RECIBO)) and TSIRE_DETALLE_PAGO.FORMA_PAGO = 44)
AND TSIRE_DETALLE_PAGO.ID_PAGO = PG.ID_PAGO
AND UR.USER_ID = U.USER_ID
AND PG.CAJERO = U.USER_ID
/*AND PG.ANULADO = 'N'*/
AND NO_RECIBO =TLIQCA_LIQUIDACION.NUMERO_RECIBO(+)
AND UR.ROLE_ID IN (69,19,68)
AND TO_TIMESTAMP(PG.FECHA_CREACION)  BETWEEN TO_TIMESTAMP('$FECHA_INICIO$', 'DD/MM/YYYY HH24:MI:SS') AND TO_TIMESTAMP('$FECHA_FIN$', 'DD/MM/YYYY HH24:MI:SS')

 --GROUP BY FORMA_PAGO.DES_PAGO,TSIRE_PAGOS.CAJERO
UNION ALL

SELECT PG.ID_PAGO AS ID_PAGO,
'open' AS GRUPO_PRODUCTO,
PG.CAJERO AS CAJERO,
(U.USER_NAME
|| ' '  
|| U.LAST_NAME) AS NOMBRE_CAJERO,
TO_CHAR(PG.FECHA_CREACION,'DD/MM/YYYY HH24:mm:ss') AS FECHA_PAGO,
--PG.FECHA_CREACION AS FECHA_PAGO,
(SYSDATE) AS FECHA_GENERACION,

-- Solo a nivel de reporte ya que todos se sigue aplicando a la cuenta origen 
DECODE(informacion_recaudo.usuario_terminal,'TU_COMPRA','TU_COMPRA',FORMA_PAGO.DES_PAGO) AS DES_PAGO,
DECODE(informacion_recaudo.usuario_terminal,'TU_COMPRA','24',FORMA_PAGO.CONSECUTIVO) AS ID_FORMA_PAGO,


(TSIRE_DETALLE_PAGO.VALOR) AS VALOR,
(SELECT SUM(VALOR)
FROM TSIRE_PAGOS P
WHERE P.NO_RECIBO=PG.NO_RECIBO
AND P.PRODUCTO =7
) AS CODIGO_BARRAS_OPEN,
(SELECT SUM(VALOR)
FROM TSIRE_PAGOS P
WHERE P.NO_RECIBO=PG.NO_RECIBO
AND P.PRODUCTO =41
) AS PAZ_ZALVO_OPEN,
(SELECT SUM(VALOR)
FROM TSIRE_PAGOS P
WHERE P.NO_RECIBO=PG.NO_RECIBO
AND P.PRODUCTO =47
) AS HONORARIOS_ABOGADO_OPEN,
(SELECT SUM(VALOR)
FROM TSIRE_PAGOS P
WHERE P.NO_RECIBO=PG.NO_RECIBO
AND P.PRODUCTO =50
) AS GASTOS_PROCESALES_OPEN_CARD,
'CAJA' AS CAJA,
UR.ROLE_ID,
NO_RECIBO AS RECIBO,
TRIM(PG.CEDULA_DEUDOR) AS CEDULA_DEUDOR,
DECODE(ANULADO,'S','ANULADO','APROBADO') AS ESTADO,
TRIM(TO_NUMBER(PG.NUMERO_COMPROBANTE)) AS COMPROBANTE,
TO_CHAR(PG.FECHA_CREACION,'HH:MI AM') AS HORA,
ID_LIQUI AS ID_LIQUIDACION,
informacion_recaudo.operador,
informacion_recaudo.usuario_terminal

FROM TSIRE_PAGOS PG,
TSIRE_DETALLE_PAGO,
TLIQCA_LIQUIDACION, 
FORMA_PAGO,
LEAF_USER U,
LEAF_USER_ROLE UR,
informacion_recaudo
WHERE 
FORMA_PAGO.CONSECUTIVO = TSIRE_DETALLE_PAGO.FORMA_PAGO
AND TSIRE_DETALLE_PAGO.ID_PAGO = PG.ID_PAGO
AND UR.USER_ID = U.USER_ID
AND PG.CAJERO = U.USER_ID
/*AND PG.ANULADO = 'N'*/
AND NO_RECIBO =TLIQCA_LIQUIDACION.NUMERO_RECIBO(+)
AND informacion_recaudo.NUMERO_RECIBO(+) = NO_RECIBO
AND UR.ROLE_ID IN (69,19,68)
AND TO_TIMESTAMP(PG.FECHA_CREACION)  BETWEEN TO_TIMESTAMP('$FECHA_INICIO$', 'DD/MM/YYYY HH24:MI:SS') AND TO_TIMESTAMP('$FECHA_FIN$', 'DD/MM/YYYY HH24:MI:SS')
--GROUP BY FORMA_PAGO.DES_PAGO,TSIRE_PAGOS.CAJERO
   
UNION ALL

SELECT P.ID_PAGO,
'aval' AS GRUPO_PRODUCTO,
U.USER_ID AS CAJERO,
(U.USER_NAME
|| ' '
|| U.LAST_NAME) AS NOMBRE_CAJERO,
TO_CHAR(P.FECHA_PAGO,'DD/MM/YYYY HH24:mm:ss') AS FECHA_PAGO,
--P.FECHA_PAGO AS FECHA_PAGO,
(SYSDATE) AS FECHA_GENERACION,

-- Solo a nivel de reporte ya que todos se sigue aplicando a la cuenta origen 
DECODE(informacion_recaudo.usuario_terminal,'TU_COMPRA','TU_COMPRA',FP.DES_PAGO) AS DES_PAGO,
DECODE(informacion_recaudo.usuario_terminal,'TU_COMPRA','24',FP.CONSECUTIVO) AS ID_FORMA_PAGO,



(F.VALOR) AS VALOR,
0 AS CODIGO_BARRAS_OPEN,
0 AS PAZ_ZALVO_OPEN,
0 AS HONORARIOS_ABOGADO_OPEN,
0 AS GASTOS_PROCESALES_OPEN_CARD,
'COBRANZAS' AS CAJA,
UR.ROLE_ID,
P.ID_PAGO AS RECIBO,
TRIM(L.CEDULAGIRADOR) AS CEDULA_DEUDOR,
DECODE(A.FECHA_ANULACION, NULL, 'APROBADO', 'ANULADO') AS ESTADO,
TRIM(L.ID_LIQUI) AS COMPROBANTE,
TO_CHAR(P.FECHA_PAGO,'HH:MI AM') AS HORA,
L.ID_LIQUI AS ID_LIQUIDACION,
informacion_recaudo.operador,
informacion_recaudo.usuario_terminal
FROM TPAGOS_PAGO P,
TPAGOS_PAGO_FORMASPAGO F,
TPAGOS_LIQUIDACION L,
TPAGOS_ANULACIONES A,
FORMA_PAGO FP,
LEAF_USER U,
LEAF_USER_INFORMATION UI,
LEAF_USER_ROLE UR,
informacion_recaudo

WHERE P.ID_PAGO = F.ID_PAGO
AND F.ID_FOPA = FP.CONSECUTIVO
AND P.ID_LIQUI =L.ID_LIQUI
AND P.ID_PAGO = A.ID_PAGO(+)
AND informacion_recaudo.NUMERO_RECIBO(+) = P.ID_PAGO 
/*    
AND NOT EXISTS
(SELECT * FROM TPAGOS_DEVOLUCIONES WHERE ID_PAGO = P.ID_PAGO
)
AND NOT EXISTS
(SELECT * FROM TPAGOS_ANULACIONES WHERE ID_PAGO = P.ID_PAGO
)*/
AND U.USER_ID = UI.USER_ID
AND UR.USER_ID = UI.USER_ID
AND UI.PROPERTY_NAME = 'IDCLFU'
AND UR.ROLE_ID IN (69,19,68)
AND P.ID_USUA = UI.PROPERTY_VALUE 
AND TO_TIMESTAMP(P.FECHA_PAGO)  BETWEEN TO_TIMESTAMP('$FECHA_INICIO$', 'DD/MM/YYYY HH24:MI:SS') AND TO_TIMESTAMP('$FECHA_FIN$', 'DD/MM/YYYY HH24:MI:SS')

	
UNION ALL 

SELECT 
 
	P.SECUENCIA AS ID_PAGO,
	'open' AS GRUPO_PRODUCTO, 
	P.ADICIONADO_POR AS CAJERO,
	P.ADICIONADO_POR AS NOMBRE_CAJERO,
    TO_CHAR(P.FECHA_ADICION,'DD/MM/YYYY HH24:mm:ss') AS FECHA_PAGO,
	--TO_CHAR(P.FECHA_ADICION,'DD/MM/YYYY') AS FECHA_PAGO,
	(SYSDATE) AS FECHA_GENERACION,
	'BANCOS ' AS DES_PAGO,
	'BANCO' AS ID_FORMA_PAGO,  
	(P.VALOR_TOTAL) AS VALOR, 
	0 AS CODIGO_BARRAS_OPEN,
	0 AS PAZ_ZALVO_OPEN,
	0 AS HONORARIOS_ABOGADO_OPEN,
	0 AS GASTOS_PROCESALES_OPEN_CARD,
	'pago_manual_open' AS CAJA, 
	0,
	TO_NUMBER(T.NUMERO_TARJETA) AS RECIBO,
	TRIM(C.NUMERO_IDENTIFICACION) AS CEDULA_DEUDOR,
	'APROBADO' AS ESTADO,
	TO_CHAR(P.SECUENCIA) AS COMPROBANTE,
	TO_CHAR(P.FECHA_ADICION,'HH:MI AM') AS  HORA,
	0 AS ID_LIQUIDACION,
    informacion_recaudo.operador,
	'' AS usuario_terminal
            
FROM 
	NU_MOVIMIENTO_DIA@OPEN_CARD P,
	NU_CLIENTES@OPEN_CARD C,
	NU_TARJETAS@OPEN_CARD T,
	informacion_recaudo
WHERE    
	T.CODIGO_CLIENTE       = C.CODIGO_CLIENTE
	AND T.CODIGO_INTERNO_TARJETA = P.CODIGO_INTERNO_TARJETA
	AND informacion_recaudo.NUMERO_RECIBO(+) = TO_NUMBER(T.NUMERO_TARJETA)
    -- AND TO_TIMESTAMP(P.FECHA_ADICION )  BETWEEN TO_TIMESTAMP_TZ('26/09/2022 00:00:00 -5:00', 'DD/MM/YYYY HH24:MI:SS TZH:TZM') AND TO_TIMESTAMP_TZ('26/09/2022 23:59:59 -5:00', 'DD/MM/YYYY HH24:MI:SS TZH:TZM')
 	AND TO_TIMESTAMP(P.FECHA_ADICION)  BETWEEN TO_TIMESTAMP_TZ('$FECHA_INICIO$ -5:00', 'DD/MM/YYYY HH24:MI:SS TZH:TZM') AND TO_TIMESTAMP_TZ('$FECHA_FIN$ -5:00', 'DD/MM/YYYY HH24:MI:SS TZH:TZM') 
    AND P.TRANSACCION_INTERNA    = 2 
     
ORDER BY HORA 